# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_insta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
