# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 12:27
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_insta', '0002_image_date_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='date_create',
            new_name='date_uploaded',
        ),
        migrations.AlterField(
            model_name='image',
            name='image_caption',
            field=tinymce.models.HTMLField(),
        ),
    ]
