# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_insta', '0003_auto_20180130_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-time_comment']},
        ),
        migrations.AddField(
            model_name='comments',
            name='time_comment',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(max_length=200),
        ),
    ]
