# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-27 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_insta', '0004_profile_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='image',
            name='comments',
        ),
        migrations.AddField(
            model_name='image',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_caption',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
