# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-27 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_insta', '0005_auto_20180127_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='images_uploaded',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_insta.Image'),
        ),
    ]
