# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-27 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_insta', '0006_profile_images_uploaded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-date_uploaded']},
        ),
    ]
