# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-27 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_insta', '0008_auto_20180127_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='images_uploaded',
        ),
    ]
