# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-27 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_insta', '0012_auto_20180127_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='comments',
        ),
        migrations.AddField(
            model_name='image',
            name='comments',
            field=models.ManyToManyField(null=True, to='my_insta.Comments'),
        ),
    ]
