# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_insta', '0015_auto_20180128_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_insta.Profile'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_caption',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
