# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_insta', '0016_auto_20180128_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
    ]
